# Generated by Django 5.0.6 on 2024-06-06 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('level', models.IntegerField(choices=[(1, 'Cycle ingénieur 1'), (2, 'Cycle ingénieur 2'), (3, 'Cycle ingénieur 3')])),
                ('subject', models.CharField(choices=[('NetArch', 'Architecture .Net et communications'), ('ClientServer', 'Client/serveur'), ('MathIA', "Mathématiques pour l'intelligence artificielle"), ('UML', 'Modélisation Objet avec UML'), ('JavaJEE', 'Java avancée et Technologies JEE'), ('DevOps1', 'DevOps 1'), ('CostManagement', 'Management des coûts'), ('LangCom3', 'Langues et communication 3'), ('FullStackPython', 'Développement Full Stack Python'), ('AngularIonic', 'Framework Angular et Ionic'), ('DevOps2', 'DevOps 2'), ('IA_BigData', "Fondements de l'IA et Big Data"), ('OracleAdmin', 'Administration Oracle'), ('LangCom4', 'Langues et communication 4'), ('TutoredProject2', 'Projet tutoré 2'), ('Cryptography', 'Cryptographie'), ('LinuxAdmin', 'Sécurité et administration Système Linux'), ('NetworkSecurity', 'Sécurité des réseaux et Cloud'), ('AppSec', 'Sécurité applicative au développent des SI'), ('ERP', 'ERP : ODOO et SAP'), ('LaborIP', 'Droit de travail et propriété intellectuelle'), ('ProjectManagement', 'Management de projets et agilité'), ('LangCom5', 'Langues et communication 5')], default='NetArch', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='courses/')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('level', models.IntegerField(blank=True, choices=[(1, '1ère année cycle ingénieur'), (2, '2ème année cycle ingénieur'), (3, '3ème année cycle ingénieur')], null=True)),
                ('enrolled_courses', models.ManyToManyField(blank=True, related_name='enrolled_students', to='education.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('recommendations', models.TextField()),
                ('student', models.ForeignKey(limit_choices_to={'is_teacher': False}, on_delete=django.db.models.deletion.CASCADE, to='education.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('subject', models.CharField(choices=[('NetArch', 'Architecture .Net et communications'), ('ClientServer', 'Client/serveur'), ('MathIA', "Mathématiques pour l'intelligence artificielle"), ('UML', 'Modélisation Objet avec UML'), ('JavaJEE', 'Java avancée et Technologies JEE'), ('DevOps1', 'DevOps 1'), ('CostManagement', 'Management des coûts'), ('LangCom3', 'Langues et communication 3'), ('FullStackPython', 'Développement Full Stack Python'), ('AngularIonic', 'Framework Angular et Ionic'), ('DevOps2', 'DevOps 2'), ('IA_BigData', "Fondements de l'IA et Big Data"), ('OracleAdmin', 'Administration Oracle'), ('LangCom4', 'Langues et communication 4'), ('TutoredProject2', 'Projet tutoré 2'), ('Cryptography', 'Cryptographie'), ('LinuxAdmin', 'Sécurité et administration Système Linux'), ('NetworkSecurity', 'Sécurité des réseaux et Cloud'), ('AppSec', 'Sécurité applicative au développent des SI'), ('ERP', 'ERP : ODOO et SAP'), ('LaborIP', 'Droit de travail et propriété intellectuelle'), ('ProjectManagement', 'Management de projets et agilité'), ('LangCom5', 'Langues et communication 5')], max_length=100)),
                ('level', models.IntegerField(choices=[(2, '2ème année cycle ingénieur'), (3, '3ème année cycle ingénieur')])),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Vidéo'), ('exercise', 'Exercice'), ('file', 'Fichier')], max_length=20)),
                ('created_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='education.submission')),
            ],
        ),
    ]
