# Generated by Django 5.0.6 on 2024-06-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='created_by',
        ),
    ]
